### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by ThalesAvila** [mindera-school/Mindera-School-5#2]
**As a** devoleper, 
**I** want a search bar, 
so that I can find projects to inspire me.

## Description
While searching developers should be able to use search term and find projects/developers related to it.

![Image](https://user-images.githubusercontent.com/8272736/221617082-caec1404-a267-4cb3-890b-01fc9651c398.png)

## Tasks
- [ ] Input for searching
- [ ] Filter by Project
- [ ] Filter by Developer
